MDL-61844 policy: Avoid to accept new policies during current session
moodlehq/moodle-tool_policy pull request #41
Opened 2018-04-04 10:58 UTC by sarjona

Removed extra-check in the handler to avoid users have to accept new policies during current session (it only happened when there were no policies and policyagreed=0).

2018-04-04 11:21 UTC, mudrd8mz commented
It seems that @marinaglancy added this check explicitly in 99b34286bb0552de9c0665e3fe6b990f955f63a0 and I suppose there was a reason for that.

2018-04-04 11:55 UTC, sarjona commented
@mudrd8mz I added some extra code in classes/output/page_agreedocs.php some days after of the commit you commented, to avoid cases like this (user->policyagreed=0 and no policies): https://github.com/moodlehq/moodle-tool_policy/commit/ae4edba94741cc05ad49bec7613f3ce95f8a68d4#diff-a1e410d368f9ba793ec97d83e1d6dd67
This commit sets user->policyagreed=1 when there are no policies... So when a new policy is activated, user->policyagreed is reset to 0, but it won't be loaded from database until next user login (user->policyagreed is stored in session).

That's why I think the extra check added initially in the handler function is no longer needed.

2018-04-04 19:38 UTC, mudrd8mz commented
Thanks Sara for working on this. However, I must admit I feel a bit unsure about this patch. I agree it seems to work. But I don't fully understand why it works. I can't trace down which particular call to this handler method triggers the redirect. My gut feeling is that we may have some missing `NO_SITEPOLICY_CHECK` somewhere.

This patch can't be accepted as it is because it would make the `handler::is_defined()` returning invalid value now (see privacy/classes/local/sitepolicy/handler.php on how the default implementation relies on the check being performed here. Which by the way we apparently do not have covered by unit tests, as they should start screaming with your patch.

2018-04-04 19:41 UTC, mudrd8mz commented
This is a patch that seems to fix the issue for me too and feels a bit more clean solution:
```
diff --git a/editpolicydoc.php b/editpolicydoc.php
index 4a9f9ac342..9dab3dc040 100644
--- a/editpolicydoc.php
+++ b/editpolicydoc.php
@@ -25,6 +25,9 @@
 use tool_policy\api;
 use tool_policy\policy_version;
 
+// Do not check for the site policies while editing them to avoid instant interruptions on activating a policy.
+define('NO_SITEPOLICY_CHECK', true);
+
 require(__DIR__.'/../../../config.php');
 require_once($CFG->libdir.'/adminlib.php');
 
diff --git a/managedocs.php b/managedocs.php
index 91e9cca39f..a567534e05 100644
--- a/managedocs.php
+++ b/managedocs.php
@@ -25,6 +25,9 @@
  * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
  */
 
+// Do not check for the site policies while editing them to avoid instant interruptions on activating a policy.
+define('NO_SITEPOLICY_CHECK', true);
+
 require(__DIR__.'/../../../config.php');
 require_once($CFG->libdir.'/adminlib.php');
```

2018-04-05 03:54 UTC, marinaglancy requested changes
Please see my comments on https://tracker.moodle.org/browse/MDL-61844

Sorry, have to reject this patch

2018-04-19 03:01 UTC, marinaglancy commented
Thanks Sara, this change is now part of another pull request, so I'm going to close this one

2018-04-19 03:01 UTC, closed without merging